### ISSUE TITLE
Outdated dependency for SpecialFunctions.jl

### ISSUE THREAD

**Issue by dgomezcastro** [JuliaMath/MittagLeffler.jl#17]
Hi! 

This is a really useful package for people in fractional ODEs. 

However it forces old versions SpecialFunctions.jl . Installing the package has caused
⌅ [276daf66] ↓ SpecialFunctions v2.3.1 ⇒ v0.10.3

Could you remove the forcing of versions here? 

I tried the code itself with 2.3.1 and it runs no problem.

Thank you,
D

**Comment by jlapeyre** [comment]
I made a new release. This should include a fix to your problem.

The release was made from my fork of the repo. MittagLeffler.jl used to live there rather than JuliaMath. The URL was never changed. (Hopefully this will be fixed before too long)

@dgomezcastro
