### ISSUE TITLE
add MittagLeffler.jl to Julia package repository

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaMath/MittagLeffler.jl#6]
Hi John,

Are you interested in adding to this to the central package repository? I am happy to add project.toml and manifest.toml files and pull request if you would like.

Thanks

Louis

**Comment by jlapeyre** [comment]
Hi Louis,
Sorry, I missed this comment earlier. Sure I would appreciate help with Project.toml, etc.
Thanks

**Comment by jlapeyre** [comment]
@JuliaRegistrator register
