### ISSUE TITLE
Numerical instability in the alpha=1/2, beta=1 special case

### ISSUE THREAD

**Issue by malacroi** [JuliaMath/MittagLeffler.jl#8]
The factorization used in the alpha=1/2, beta=1 special case is instable for z of large magnitude.  For this special case, the function is defined by a factorization:
  α == 1/2 && return exp(z^2)*erfc(-z)
that is degenerate for z of moderate magnitude, where the generic implementation remains robust.

Contrast
mittleff(0.50001,1,-30) = 0.01879554175839369
mittleff(0.50000,1,-30) = NaN
mittleff(0.50000,1,BigFloat(-30)) = 0.018795888861416751497125329049406209...
mittleff(0.49999,1,-30) = 0.018796235961980556

In the second case, we have exp(900) = Inf and erfc(30) = 0.0.  Would it be reasonable to check that the factorization does not encounter this undefined form, and fall back on the generic computation if it does?

**Comment by jlapeyre** [comment]
Thanks for bringing this up. It is fixed in master
